"""add user name

Revision ID: 1933cfc554e9
Revises: 6f961eb2b5c7
Create Date: 2023-11-22 11:45:55.806604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1933cfc554e9'
down_revision: Union[str, None] = '6f961eb2b5c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('UserName', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'UserName')
    # ### end Alembic commands ###
